name: render-student-into

run-name: Running Quarto Render on Markdown File

on: [push]

env:
  MARKDOWN_DOCUMENT: introduction.qmd
  
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Checkout Assignment Repository
        uses: actions/checkout@v4

      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: DSPG-2025/Private-Blog
          token: ${{ secrets.BLOG_PAT_TOKEN }}
          path: DSPG-2025/Private-Blog     

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: "true"
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'          

      - name: View Repository Directories
        run: |
          ls -la
        
      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: "always"
        
      - name: Install Quarto CLI
        run: |
          wget https://quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
          quarto check install
          
      - name: Render QMD File
        run: |
          quarto render introduction.qmd --to html

      - name: Copy Markdown Files and Folders and Push
        if: success()
        env:
          GH_PAT: ${{ secrets.BLOG_PAT_TOKEN }}
        run: |
          echo "ATTEMPTING FILE PUSH"
          cd DSPG-2025/Private-Blog/Assignments/
          rm -rf ${{ github.event.repository.name }} || true 
          mkdir ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
          cp ../../../../Weekly_Team_Blog.qmd .
          cp -r ../../../../Data/ ./Data
          cp -r ../../../../imgs ./imgs
          git add .
          git status 
          git commit -m "Add markdown file output, data folder, and images of ${{ github.actor }}"
          git push https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/DSPG-2025/Private-Blog.git
