name: render-student-intro

run-name: Running Quarto Render on Markdown File

on: [push]

env:
  MARKDOWN_DOCUMENT: introduction.qmd
  
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Checkout Assignment Repository
        uses: actions/checkout@v4

      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: DSPG-2025/Private-Blogs
          token: ${{ secrets.BLOG_PAT_TOKEN }}
          path: DSPG-2025/Private-Blogs             

      - name: View Repository Directories
        run: |
          ls -la
        
      - name: Set-Up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          
      - name: Render QMD File
        run: |
          quarto render $MARKDOWN_DOCUMENT --to html

      - name: Copy Markdown Files and Folders and Push
        if: success()
        env:
          GH_PAT: ${{ secrets.BLOG_PAT_TOKEN }}
        run: |
          echo "ATTEMPTING FILE PUSH"
          cd DSPG-2025/Private-Blogss/Assignments/
          rm -rf ${{ github.event.repository.name }} || true 
          mkdir ${{ github.event.repository.name }}
          cd ${{ github.event.repository.name }}
          cp ../../../../$MARKDOWN_DOCUMENT .
          cp -r ../../../../Data/ ./Data
          cp -r ../../../../imgs ./imgs
          git add .
          git status 
          git commit -m "Add markdown file output, data folder, and images of ${{ github.actor }}"
          git push https://${{ github.actor }}:${{ secrets.GH_PAT }}@github.com/DSPG-2025/Private-Blogss.git
